---
title: "Appendix"
author: "Katarina Matthes"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r global_options, include=FALSE,message=FALSE}
used.data <- databern %>%
       filter(multiple==0) %>%
       filter(!(weight < 1500)) %>%
       filter(!(matage > 50))  %>%
       filter(!(matage <14)) %>%
   filter(!(gest <30)) %>%
  mutate(
   year = as.factor(year),
   boy = as.factor(boy),
   stillborn = as.factor(stillborn),
   city = as.factor(city),
   insurance = as.factor(insurance),
   married = as.factor(married),
   matbody2 = as.factor(matbody2),
   occupation2 = as.factor(occupation2),
   matheight2  = as.factor(matheight2 ),
   malnutrition2 = as.factor(malnutrition2),
   Gest_group = factor(Gest_group, levels=c("normal","early")),
   parity = factor(parity, levels=c("1","2","3",">=4")),
   city = factor(city, levels=c("1","0")),
   married = factor(married, levels=c("1","0")),
   boy = factor(boy, levels=c("1","0")),
   birth_season = factor( birth_season, levels=c("Spring","Summer","Fall","Winter")),
   parity = factor(parity, levels = c("1","2","3",">=4")),
   matbody2 = factor(matbody2, levels=c("2","1","3")),
   matheight2 = factor(matheight2, levels=c("2","1","3")),
   malnutrition2 = factor(malnutrition2, levels=c("0","1")),
   occupation2 = factor(occupation2, levels=c("4","1","2","3","5","6","7")),
   Exposure_sum_dummy = as.factor(Exposure_sum_dummy)
  )
```

# Flu Intensity Trimester

## First Trimester

### Birth weight

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_quantile_regression_trimester(varExp="Flu_intensity_first")
```

### Gestational Age

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_regression_gestage_trimester(varExp="Flu_intensity_first")
```


### Stillborn

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_regression_stillborn_trimester(varExp="Flu_intensity_first")
```


## Second Trimester

### Birth weight

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_quantile_regression_trimester(varExp="Flu_intensity_second")
```

### Gestational Age
```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_regression_gestage_trimester(varExp="Flu_intensity_second")
```

### Stillborn

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_regression_stillborn_trimester(varExp="Flu_intensity_second")
```


## Third Trimester

### Birth weight

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_quantile_regression_trimester(varExp="Flu_intensity_third")
```

### Gestational Age
```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_regression_gestage_trimester(varExp="Flu_intensity_third")
```

### Stillborn

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_regression_stillborn_trimester(varExp="Flu_intensity_third")
```
