---
title: "Birthweights 1880 - 1900"
author: "Katarina Matthes"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r global_options, include=FALSE,message=FALSE}
used.data <- databern %>%
       filter(multiple==0) %>%
       filter(!(weight < 1000)) %>%
       filter(!(matage > 50))  %>%
       filter(!(matage <14)) %>%
   filter(!(gest <30)) %>%
  mutate(
   year = as.factor(year),
   boy = as.factor(boy),
   stillborn = as.factor(stillborn),
   city = as.factor(city),
   insurance = as.factor(insurance),
   married = as.factor(married),
   matbody2 = as.factor(matbody2),
   occupation2 = as.factor(occupation2),
   matheight2  = as.factor(matheight2 ),
   malnutrition2 = as.factor(malnutrition2),
   Gest_group = factor(Gest_group, levels=c("normal","early")),
   parity = factor(parity, levels=c("1","2","3",">=4")),
   city = factor(city, levels=c("1","0")),
   married = factor(married, levels=c("1","0")),
   boy = factor(boy, levels=c("1","0")),
   birth_season = factor( birth_season, levels=c("Spring","Summer","Fall","Winter")),
   parity = factor(parity, levels = c("1","2","3",">=4")),
   matbody2 = factor(matbody2, levels=c("2","1","3")),
   matheight2 = factor(matheight2, levels=c("2","1","3")),
   malnutrition2 = factor(malnutrition2, levels=c("0","1")),
   occupation2 = factor(occupation2, levels=c("4","1","2","3","5","6","7")),
   Exposure_sum_dummy = as.factor(Exposure_sum_dummy)
  )
```

# Birth weights


## unadjusted


### Quantile regression  

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_quantile_regression_1880(varExp="unadjusted_year_qr")
```


### Year

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_year_linear")
```

### Sex

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_boy_linear")
```

### Parity

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_parity_linear")
```

### Gestational age

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_gest_linear")
```


### Birth month

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_month_linear")
```

### Maternal height

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_matheight_linear")
```


### Malnutrition

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_malnutrition_linear")
```


### Maternal bodysize

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_matbody_linear")
```

### Occupation

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_occupation_linear")
```


### Maternal Age

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_matage_linear")
```

### Age menarche

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_agemenarche_linear")
```


### City

```{r, echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5 ,fig.width = 5}
function_quantile_regression_1880(varExp="unadjusted_city_linear")
```

<!-- GAM regression  -->
<!-- <br /> -->
<!-- <br /> -->
<!-- ```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 8} -->
<!-- function_quantile_regression_1880(varExp="unadjusted_gam_model") -->
<!-- ``` -->

<!-- ```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 8} -->
<!-- function_quantile_regression_1880(varExp="unadjusted_gam_model_plot") -->
<!-- ``` -->

## adjusted 

### Quantile regression  

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 8}
function_quantile_regression_1880(varExp="adjusted_year_qr")
```

### Parity
```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 8}
function_quantile_regression_1880(varExp="adjusted_linear")
```

```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 8}
function_quantile_regression_1880(varExp="adjusted_linear_plot")
```


### Occupation
```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 8}
function_quantile_regression_1880(varExp="adjusted_linear_occupation")
```


## Logistic Regression
<2500 g low birth weight

### unadjusted
Year
```{r, echo=FALSE, message=TRUE,warning=FALSE}
function_regression_lbw(varExp= "unadjusted")
```

```{r, echo=FALSE, message=TRUE,warning=FALSE}
function_regression_lbw(varExp= "unadjusted_plot")
```

### adjusted

```{r, echo=FALSE, message=TRUE,warning=FALSE}
function_regression_lbw(varExp= "adjusted")
```

```{r, echo=FALSE, message=TRUE,warning=FALSE}
function_regression_lbw(varExp= "adjusted_plot")
```


<!-- GAM regression  -->
<!-- <br /> -->
<!-- <br /> -->
<!-- ```{r, echo=FALSE, message=TRUE,warning=FALSE} -->
<!-- function_quantile_regression_1880(varExp="adjusted_gam") -->
<!-- ``` -->

<!-- ```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 8} -->
<!-- function_quantile_regression_1880(varExp="adjusted_gam_plot") -->
<!-- ``` -->


<!-- # Gestational age -->

<!-- ## unadjusted -->
<!-- <br /> -->
<!-- <br /> -->

<!-- ```{r, echo=FALSE, message=TRUE,warning=FALSE} -->
<!-- function_regression_gestage_1880(varExp="unadjusted") -->
<!-- ``` -->

<!-- ```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 5} -->
<!-- function_regression_gestage_1880(varExp="unadjusted_plot") -->
<!-- ``` -->


<!-- ## adjusted -->
<!-- <br /> -->
<!-- <br /> -->
<!-- year -->
<!-- ```{r, echo=FALSE,message=TRUE,warning=FALSE} -->
<!-- function_regression_gestage_1880(varExp="adjusted") -->
<!-- ``` -->

<!-- ```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 5} -->
<!-- function_regression_gestage_1880(varExp="adjusted_plot") -->
<!-- ``` -->

<!-- # Stillborn -->

<!-- ## unadjusted -->

<!-- <br /> -->
<!-- <br /> -->
<!-- ```{r, echo=FALSE, message=TRUE,warning=FALSE} -->
<!-- function_regression_stillborn_1880(varExp="unadjusted") -->
<!-- ``` -->

<!-- ```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 5, fig.width = 5} -->
<!-- function_regression_stillborn_1880(varExp="unadjusted_plot") -->
<!-- ``` -->

<!-- ## adjusted -->

<!-- <br /> -->
<!-- <br /> -->
<!-- ```{r, echo=FALSE,message=TRUE,warning=FALSE} -->
<!-- function_regression_stillborn_1880(varExp="adjusted_year") -->
<!-- ``` -->

<!-- ```{r , echo=FALSE, message=FALSE,warning=FALSE,fig.height = 8, fig.width = 5} -->
<!-- function_regression_stillborn_1880(varExp="adjusted_year_plot") -->
<!-- ``` -->